import ICON_BOOKMARK from './ICON_BOOKMARK'
import ICON_GITHUB from './ICON_GITHUB'
import ICON_GNB_1 from './ICON_GNB_1'
import ICON_GNB_2 from './ICON_GNB_2'
import ICON_GOOGLE from './ICON_GOOGLE'
import ICON_KAKAO from './ICON_KAKAO'
import ICON_LOGO from './ICON_LOGO'
import ICON_NAVER from './ICON_NAVER'

export { ICON_BOOKMARK,ICON_GITHUB, ICON_GNB_1, ICON_GNB_2, ICON_GOOGLE, ICON_KAKAO, ICON_LOGO, ICON_NAVER }
